/**
 * Generates the UnoCSS output for the ipod-wc shadow-DOM context and writes it
 * to src/uno-generated.ts as a typed string export. The Lit stageStyles block
 * imports this and wraps it in `unsafeCSS()` so it lives inside the shadow root.
 *
 * Run: node packages/ipod-wc/scripts/generate-uno.mjs
 */
import { createGenerator } from "unocss";
import { presetWind3, presetIcons } from "unocss";
import { readFileSync, writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dir = dirname(fileURLToPath(import.meta.url));
const srcDir = join(__dir, "..", "src");

// Scan source files for utility class names
const sourceFiles = ["ipod-classic.ts", "stage-css.ts"].map((f) =>
	readFileSync(join(srcDir, f), "utf8"),
);

const uno = await createGenerator({
	presets: [presetWind3(), presetIcons({ scale: 1.2 })],
	// shadow-dom: generate self-contained CSS without the global cascade
	theme: {},
});

const { css } = await uno.generate(sourceFiles.join("\n"), {
	preflights: false, // host page owns resets; shadow root inherits what it needs
	minify: false,
});

const banner = `// AUTO-GENERATED by packages/ipod-wc/scripts/generate-uno.mjs — do not edit.
// Re-run after adding utility classes to ipod-classic.ts.
`;
const output = `${banner}export const UNO_CSS = ${JSON.stringify(css)};\n`;

const outPath = join(srcDir, "uno-generated.ts");
writeFileSync(outPath, output, "utf8");
console.log(`✓ UnoCSS shadow-dom output written to ${outPath} (${css.length} bytes)`);
