#!/usr/bin/env bun
/**
 * Extract design tokens from tailwind.config.ts and app/globals.css into
 * a W3C DTCG JSON file at design-tokens/tokens.json.
 *
 * Source of truth is code — this script is deterministic and idempotent.
 * Running it twice in a row produces zero diff unless the source files have
 * changed. CI freshness check (`scripts/check-tokens-fresh.ts`) runs this
 * script with `--stdout` and compares against the committed JSON.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

type DtcgColorValue = string | { light: string; dark: string };

interface DtcgToken {
	$type: "color" | "dimension" | "string";
	$value: DtcgColorValue | string;
	$description?: string;
}

interface DtcgGroup {
	[key: string]: DtcgToken | DtcgGroup;
}

interface TokensJson {
	$schema: string;
	$description: string;
	Primitives: DtcgGroup;
	Semantic: DtcgGroup;
	Component: DtcgGroup;
}

const REPO_ROOT = resolve(import.meta.dir, "..");
const GLOBALS_CSS = resolve(REPO_ROOT, "app/globals.css");
const TOKENS_JSON = resolve(REPO_ROOT, "design-tokens/tokens.json");

const DTCG_SCHEMA =
	"https://raw.githubusercontent.com/design-tokens/community-group/main/packages/format/schemas/tokens.schema.json";

const SEMANTIC_COLOR_KEYS = [
	"background",
	"foreground",
	"card",
	"card-foreground",
	"popover",
	"popover-foreground",
	"primary",
	"primary-foreground",
	"secondary",
	"secondary-foreground",
	"muted",
	"muted-foreground",
	"accent",
	"accent-foreground",
	"destructive",
	"destructive-foreground",
	"border",
	"input",
	"ring",
] as const;

function extractCssBlock(css: string, selector: string): Record<string, string> {
	// Capture the first matching block. The source file uses @layer base { ... }
	// wrappers but the selector is unique enough to anchor on.
	const escaped = selector.replace(/[-[\]/{}()*+?.\\^$|]/g, "\\$&");
	const blockRe = new RegExp(`${escaped}\\s*\\{([\\s\\S]*?)\\}`);
	const match = css.match(blockRe);
	if (!match) {
		throw new Error(
			`[extract-tokens] could not find CSS block for selector "${selector}" in app/globals.css`,
		);
	}
	const body = match[1];
	const entries: Record<string, string> = {};
	const declRe = /--([a-zA-Z0-9-]+)\s*:\s*([^;]+);/g;
	let m: RegExpExecArray | null;
	while ((m = declRe.exec(body)) !== null) {
		entries[m[1]] = m[2].trim();
	}
	return entries;
}

function hslValue(raw: string): string {
	// Normalize to `hsl(<raw>)` so Figma receives a parseable color.
	return `hsl(${raw})`;
}

function validateColor(value: string, name: string): void {
	if (value === "not-a-color" || value === "") {
		throw new Error(
			`[extract-tokens] invalid color for ${name}: ${JSON.stringify(value)}`,
		);
	}
}

function buildSemanticColors(
	light: Record<string, string>,
	dark: Record<string, string>,
): DtcgGroup {
	const group: DtcgGroup = {};
	for (const key of SEMANTIC_COLOR_KEYS) {
		const lightRaw = light[key];
		const darkRaw = dark[key];
		if (!lightRaw || !darkRaw) {
			throw new Error(
				`[extract-tokens] missing color token "${key}" in one of :root / .dark`,
			);
		}
		validateColor(lightRaw, `color.${key}:light`);
		validateColor(darkRaw, `color.${key}:dark`);
		group[key] = {
			$type: "color",
			$value: {
				light: hslValue(lightRaw),
				dark: hslValue(darkRaw),
			},
		};
	}
	return group;
}

function buildRadiusGroup(light: Record<string, string>): DtcgGroup {
	const base = light["radius"] ?? "0.5rem";
	return {
		lg: { $type: "dimension", $value: base },
		md: { $type: "dimension", $value: `calc(${base} - 2px)` },
		sm: { $type: "dimension", $value: `calc(${base} - 4px)` },
	};
}

function buildTokens(): TokensJson {
	const css = readFileSync(GLOBALS_CSS, "utf8");
	const lightVars = extractCssBlock(css, ":root");
	const darkVars = extractCssBlock(css, ".dark");

	return {
		$schema: DTCG_SCHEMA,
		$description:
			"iPod design tokens extracted from tailwind.config.ts and app/globals.css. Source of truth is code — this file is regenerated by `bun run tokens:extract`. Do not hand-edit.",
		Primitives: {
			color: {
				white: { $type: "color", $value: "#FFFFFF" },
				black: { $type: "color", $value: "#000000" },
			},
			radius: {
				base: {
					$type: "dimension",
					$value: lightVars["radius"] ?? "0.5rem",
				},
			},
		},
		Semantic: {
			color: buildSemanticColors(lightVars, darkVars),
			radius: buildRadiusGroup(lightVars),
		},
		Component: {
			ipod: {
				shell: {
					"default-black": {
						$type: "color",
						$value: "#1A1A1A",
						$description:
							"Default shell color for the 2008 Black preset",
					},
					"default-silver": {
						$type: "color",
						$value: "#C8C9CB",
						$description:
							"Default shell color for the 2008 Silver preset",
					},
				},
				backdrop: {
					default: {
						$type: "color",
						$value: "#FFFFFF",
						$description:
							"Default backdrop color for the staging frame",
					},
				},
			},
		},
	};
}

function main(): void {
	const tokens = buildTokens();
	const serialized = JSON.stringify(tokens, null, 2) + "\n";

	if (process.argv.includes("--stdout")) {
		process.stdout.write(serialized);
		return;
	}

	writeFileSync(TOKENS_JSON, serialized, "utf8");
	// eslint-disable-next-line no-console
	console.log(`[extract-tokens] wrote ${TOKENS_JSON}`);
}

main();
