// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as MoonBitBindings from "./MoonBitBindings.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as JsxRuntime from "react/jsx-runtime";

function ClickWheel(props) {
  let dispatch = props.dispatch;
  let skinColor = props.skinColor;
  let wheelRef = React.useRef(null);
  let lastAngle = React.useRef(0.0);
  let accumulated = React.useRef(0.0);
  let tracking = React.useRef(false);
  let wheelColors = React.useMemo(() => MoonBitBindings.deriveWheelColors(skinColor), [skinColor]);
  let getCenter = () => {
    let el = wheelRef.current;
    if (el == null) {
      return [
        0.0,
        0.0
      ];
    }
    let rect = el.getBoundingClientRect();
    return [
      rect.left + rect.width / 2.0,
      rect.top + rect.height / 2.0
    ];
  };
  let normalizeDelta = delta => {
    if (delta > Math.PI) {
      return delta - 2.0 * Math.PI;
    } else if (delta < - Math.PI) {
      return delta + 2.0 * Math.PI;
    } else {
      return delta;
    }
  };
  let onPointerDown = e => {
    let match = getCenter();
    let angle = Math.atan2(e.clientY - match[1], e.clientX - match[0]);
    lastAngle.current = angle;
    accumulated.current = 0.0;
    tracking.current = true;
    let el = wheelRef.current;
    if (!(el == null)) {
      return el.setPointerCapture(e.pointerId);
    }
  };
  let onPointerMove = e => {
    if (!tracking.current) {
      return;
    }
    let match = getCenter();
    let angle = Math.atan2(e.clientY - match[1], e.clientX - match[0]);
    let rawDelta = angle - lastAngle.current;
    let delta = normalizeDelta(rawDelta);
    lastAngle.current = angle;
    let newAcc = accumulated.current + delta;
    accumulated.current = newAcc;
    let degrees = newAcc * 180.0 / Math.PI;
    if (Math.abs(degrees) < 30.0) {
      return;
    }
    let steps = degrees / 30.0 | 0;
    dispatch({
      TAG: "CycleOsMenu",
      _0: steps
    });
    accumulated.current = newAcc - steps * 30.0 * Math.PI / 180.0;
  };
  let onPointerUp = _e => {
    tracking.current = false;
  };
  let onCenterClick = _e => dispatch({
    TAG: "SetOsScreen",
    _0: "NowPlaying"
  });
  let labelStyle = {
    color: wheelColors.labelColor,
    fontSize: "11px",
    fontWeight: "600"
  };
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: "MENU",
        className: "wheel-btn menu-btn",
        style: labelStyle
      }),
      JsxRuntime.jsx("div", {
        children: "MID.",
        className: "wheel-btn prev-btn",
        style: labelStyle
      }),
      JsxRuntime.jsx("div", {
        children: "MID.",
        className: "wheel-btn next-btn",
        style: labelStyle
      }),
      JsxRuntime.jsx("div", {
        children: "MID.",
        className: "wheel-btn pp-btn",
        style: labelStyle
      }),
      JsxRuntime.jsx("div", {
        className: "wheel-center",
        style: {
          borderColor: wheelColors.centerBorder,
          background: wheelColors.centerGradient
        },
        onClick: onCenterClick
      })
    ],
    ref: Primitive_option.some(wheelRef),
    className: "click-wheel",
    onPointerDown: onPointerDown,
    onPointerMove: onPointerMove,
    onPointerUp: onPointerUp
  });
}

let make = ClickWheel;

export {
  make,
}
/* react Not a pure module */
