// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as MoonBitBindings from "./MoonBitBindings.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function ColorPicker(props) {
  let dispatch = props.dispatch;
  let skinColor = props.skinColor;
  let finishes = React.useMemo(() => MoonBitBindings.authenticFinishes(), []);
  return JsxRuntime.jsx("div", {
    children: JsxRuntime.jsx("div", {
      children: Belt_Array.map(finishes, f => {
        let active = f.hex === skinColor;
        return JsxRuntime.jsx("div", {
          className: active ? "swatch swatch-active" : "swatch",
          style: {
            backgroundColor: f.hex
          },
          title: f.label,
          onClick: param => dispatch({
            TAG: "SetSkinColor",
            _0: f.hex
          })
        }, f.hex);
      }),
      className: "swatch-grid"
    }),
    className: "color-picker"
  });
}

let make = ColorPicker;

export {
  make,
}
/* react Not a pure module */
