// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function Editors(props) {
  let event = props.event;
  let dispatch = props.dispatch;
  let value = props.value;
  let match = React.useState(() => false);
  let setEditing = match[1];
  let editing = match[0];
  let match$1 = React.useState(() => value);
  let setEditValue = match$1[1];
  let editValue = match$1[0];
  React.useRef(null);
  let save = () => {
    if (editing) {
      dispatch(event(editValue));
      return setEditing(param => false);
    }
  };
  let onKeyDown = e => {
    if (e.key === "Enter") {
      e.preventDefault();
      return save();
    } else if (e.key === "Escape") {
      setEditValue(param => value);
      return setEditing(param => false);
    } else {
      return;
    }
  };
  if (editing) {
    return JsxRuntime.jsx("input", {
      className: "editor-input",
      autoFocus: true,
      type: "text",
      value: editValue,
      onKeyDown: onKeyDown,
      onBlur: param => save(),
      onChange: e => {
        let target = e.target;
        setEditValue(param => target.value);
      }
    });
  } else {
    return JsxRuntime.jsx("span", {
      children: value,
      className: "editor-display",
      title: "Double-click to edit " + props.field,
      onDoubleClick: param => {
        setEditValue(param => value);
        setEditing(param => true);
      }
    });
  }
}

let make = Editors;

export {
  make,
}
/* react Not a pure module */
