// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Storage from "./Storage.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";

function run(effects, _model) {
  Belt_Array.forEach(effects, e => {
    switch (e) {
      case "PERSIST_METADATA" :
        return Storage.setMetadata(_model.metadata);
      case "PERSIST_UI_STATE" :
        return Storage.setUiState(_model.presentation, _model.interaction);
      default:
        return;
    }
  });
}

export {
  run,
}
/* No side effect */
