// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Effects from "./Effects.mjs";
import * as Storage from "./Storage.mjs";
import * as IpodDevice from "./IpodDevice.mjs";
import * as MoonBitBindings from "./MoonBitBindings.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Index(props) {
  let m = Storage.loadModel();
  let initialModel = m !== undefined ? m : MoonBitBindings.defaultModel();
  let match = React.useReducer((state, action) => {
    let result = MoonBitBindings.reduce(state, action);
    Effects.run(result.effects, result.model);
    return result.model;
  }, initialModel);
  return JsxRuntime.jsx(IpodDevice.make, {
    model: match[0],
    dispatch: match[1]
  });
}

let make = Index;

export {
  make,
}
/* react Not a pure module */
