// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Editors from "./Editors.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as MarqueeText from "./MarqueeText.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function IpodScreen(props) {
  let dispatch = props.dispatch;
  let model = props.model;
  let meta = model.metadata;
  let inter = model.interaction;
  let pb = model.playback;
  let formatTime = secs => {
    let m = secs / 60.0 | 0;
    let s = secs % 60.0 | 0;
    let sStr = s < 10 ? "0" + s.toString() : s.toString();
    return m.toString() + ":" + sStr;
  };
  let batteryPct = inter.batteryLevel * 100.0 | 0;
  let batteryBars = inter.batteryLevel * 5.0 | 0;
  let bars = Belt_Array.reduce(Belt_Array.makeBy(batteryBars, param => "|"), "", (a, b) => a + b);
  let progressPct = pb.duration > 0.0 ? pb.currentTime / pb.duration * 100.0 : 0.0;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("span", {
            children: "Now Playing"
          }),
          JsxRuntime.jsx("span", {
            children: bars + " " + batteryPct.toString() + "%",
            style: {
              color: inter.batteryLevel > 0.2 ? "#4CAF50" : "#f44336",
              fontFamily: "monospace"
            }
          })
        ],
        className: "status-bar"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: meta.artwork === "" ? JsxRuntime.jsx("div", {
                children: "🎵",
                className: "artwork-placeholder"
              }) : JsxRuntime.jsx("img", {
                className: "artwork-img",
                alt: "Album Art",
                src: meta.artwork
              }),
            className: "artwork-column"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("div", {
                children: JsxRuntime.jsx(MarqueeText.make, {
                  text: meta.title,
                  containerWidth: 130.0
                }),
                className: "song-title"
              }),
              JsxRuntime.jsx("div", {
                children: JsxRuntime.jsx(Editors.make, {
                  field: "artist",
                  value: meta.artist,
                  dispatch: dispatch,
                  event: v => ({
                    TAG: "UpdateArtist",
                    _0: v
                  })
                }),
                className: "song-artist"
              }),
              JsxRuntime.jsx("div", {
                children: JsxRuntime.jsx(Editors.make, {
                  field: "album",
                  value: meta.album,
                  dispatch: dispatch,
                  event: v => ({
                    TAG: "UpdateAlbum",
                    _0: v
                  })
                }),
                className: "song-album"
              }),
              JsxRuntime.jsx("div", {
                children: "Track " + meta.trackNumber.toString() + " of " + meta.totalTracks.toString(),
                className: "meta-row"
              })
            ],
            className: "track-info"
          })
        ],
        className: "now-playing-content"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: JsxRuntime.jsx("div", {
              className: "progress-fill",
              style: {
                width: progressPct.toString() + "%"
              }
            }),
            className: "progress-bar"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("span", {
                children: formatTime(pb.currentTime)
              }),
              JsxRuntime.jsx("span", {
                children: "-" + formatTime(pb.duration - pb.currentTime)
              })
            ],
            className: "time-row"
          })
        ],
        className: "progress-container"
      }),
      JsxRuntime.jsx("div", {
        className: "pointer-events-none absolute",
        style: {
          position: "absolute",
          inset: "0",
          background: "linear-gradient(135deg, rgba(255,255,255,0.12) 0%, rgba(255,255,255,0.03) 30%, rgba(255,255,255,0) 50%, rgba(255,255,255,0.05) 100%)"
        }
      }),
      JsxRuntime.jsx("div", {
        className: "pointer-events-none absolute",
        style: {
          position: "absolute",
          left: "5%",
          top: "4%",
          height: "40%",
          width: "50%",
          borderRadius: "20px",
          opacity: "0.2",
          background: "linear-gradient(160deg, rgba(255,255,255,0.1) 0%, rgba(255,255,255,0.02) 25%, rgba(255,255,255,0) 65%)"
        }
      }),
      JsxRuntime.jsx("div", {
        className: "pointer-events-none absolute",
        style: {
          position: "absolute",
          inset: "0",
          boxShadow: "inset 0 1px 4px rgba(0,0,0,0.15)"
        }
      })
    ],
    className: "screen",
    style: {
      width: "296px",
      height: "222px",
      backgroundColor: "#fff"
    }
  });
}

let make = IpodScreen;

export {
  make,
}
/* Editors Not a pure module */
