// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Editors from "./Editors.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function IpodScreen(props) {
  let dispatch = props.dispatch;
  let model = props.model;
  let meta = model.metadata;
  let inter = model.interaction;
  let pb = model.playback;
  let formatTime = secs => {
    let m = secs / 60.0 | 0;
    let s = secs % 60.0 | 0;
    let sStr = s < 10 ? "0" + s.toString() : s.toString();
    return m.toString() + ":" + sStr;
  };
  let batteryPct = inter.batteryLevel * 100.0 | 0;
  let batteryBars = inter.batteryLevel * 5.0 | 0;
  let batteryColor = batteryPct > 20 ? "#4CAF50" : "#f44336";
  let bars = Belt_Array.reduce(Belt_Array.makeBy(batteryBars, param => "|"), "", (a, b) => a + b);
  let progressPct = pb.duration > 0.0 ? pb.currentTime / pb.duration * 100.0 : 0.0;
  let stars = Belt_Array.reduce(Belt_Array.makeBy(meta.rating, param => "*"), "", (a, b) => a + b);
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("span", {
            children: "Now Playing"
          }),
          JsxRuntime.jsx("span", {
            children: bars + " " + batteryPct.toString() + "%",
            className: "battery",
            style: {
              color: batteryColor
            }
          })
        ],
        className: "status-bar"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          meta.artwork === "" ? JsxRuntime.jsx("div", {
              children: "🎵",
              className: "artwork-placeholder"
            }) : JsxRuntime.jsx("img", {
              className: "artwork-img",
              alt: "Album Art",
              src: meta.artwork
            }),
          JsxRuntime.jsx("div", {
            children: JsxRuntime.jsx(Editors.make, {
              field: "title",
              value: meta.title,
              dispatch: dispatch,
              event: v => ({
                TAG: "UpdateTitle",
                _0: v
              })
            }),
            className: "song-title"
          }),
          JsxRuntime.jsx("div", {
            children: JsxRuntime.jsx(Editors.make, {
              field: "artist",
              value: meta.artist,
              dispatch: dispatch,
              event: v => ({
                TAG: "UpdateArtist",
                _0: v
              })
            }),
            className: "song-artist"
          }),
          JsxRuntime.jsx("div", {
            children: JsxRuntime.jsx(Editors.make, {
              field: "album",
              value: meta.album,
              dispatch: dispatch,
              event: v => ({
                TAG: "UpdateAlbum",
                _0: v
              })
            }),
            className: "song-album"
          }),
          JsxRuntime.jsx("div", {
            children: stars + " " + meta.rating.toString() + "/5 - Track " + meta.trackNumber.toString() + " of " + meta.totalTracks.toString(),
            className: "meta-row"
          }),
          JsxRuntime.jsx("div", {
            children: JsxRuntime.jsx("div", {
              className: "progress-fill",
              style: {
                width: progressPct.toString() + "%"
              }
            }),
            className: "progress-bar"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("span", {
                children: formatTime(pb.currentTime)
              }),
              JsxRuntime.jsx("span", {
                children: "-" + formatTime(pb.duration - pb.currentTime)
              })
            ],
            className: "time-row"
          })
        ],
        className: "now-playing"
      })
    ],
    className: "screen"
  });
}

let make = IpodScreen;

export {
  make,
}
/* Editors Not a pure module */
