// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ClickWheel from "./ClickWheel.mjs";
import * as IpodScreen from "./IpodScreen.mjs";
import * as ColorPicker from "./ColorPicker.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function IpodDevice(props) {
  let dispatch = props.dispatch;
  let model = props.model;
  let skinColor = model.presentation.skinColor;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: JsxRuntime.jsx(IpodScreen.make, {
          model: model,
          dispatch: dispatch
        }),
        className: "screen-frame"
      }),
      JsxRuntime.jsx(ClickWheel.make, {
        skinColor: skinColor,
        dispatch: dispatch
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("button", {
            children: model.interaction.isPlaying ? "Pause" : "Play",
            onClick: param => dispatch("ToggleIsPlaying")
          }),
          JsxRuntime.jsx("button", {
            children: "Reset",
            onClick: param => dispatch("ResetModel")
          })
        ],
        className: "controls"
      }),
      JsxRuntime.jsx(ColorPicker.make, {
        skinColor: skinColor,
        dispatch: dispatch
      }),
      JsxRuntime.jsx("div", {
        children: "Powered by MoonBit",
        className: "info-bar"
      })
    ],
    className: "ipod",
    style: {
      backgroundColor: skinColor
    }
  });
}

let make = IpodDevice;

export {
  make,
}
/* ClickWheel Not a pure module */
