// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as MoonBitBindings from "./MoonBitBindings.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as JsxRuntime from "react/jsx-runtime";

function MarqueeText(props) {
  let containerWidth = props.containerWidth;
  let text = props.text;
  let textRef = React.useRef(null);
  let match = React.useState(() => 0.0);
  let match$1 = React.useState(() => false);
  let setNeedsScroll = match$1[1];
  let animFrameRef = React.useRef(undefined);
  let cycleRef = React.useRef(0.0);
  let startRef = React.useRef(0.0);
  React.useEffect(() => {
    let el = textRef.current;
    if (!(el == null)) {
      let textWidth = el.offsetWidth;
      let gap = MoonBitBindings.marqueeCycleMs(textWidth, containerWidth, containerWidth * 0.25);
      let needed = MoonBitBindings.marqueeNeeded(textWidth, containerWidth);
      setNeedsScroll(param => needed);
      if (needed) {
        cycleRef.current = gap;
        let start = (Date.now());
        startRef.current = start;
        let id = (requestAnimationFrame(animate));
        animFrameRef.current = Primitive_option.some(id);
      }
    }
    return () => {
      let id = animFrameRef.current;
      if (id !== undefined) {
        ((cancelAnimationFrame(id)));
        return;
      }
    };
  }, []);
  if (match$1[0]) {
    return JsxRuntime.jsx("div", {
      children: JsxRuntime.jsxs("div", {
        children: [
          text,
          JsxRuntime.jsx("span", {
            children: text,
            style: {
              marginLeft: "60px"
            }
          })
        ],
        ref: Primitive_option.some(textRef),
        style: {
          transform: "translateX(" + match[0].toString() + "px)",
          whiteSpace: "nowrap"
        }
      }),
      style: {
        overflow: "hidden"
      }
    });
  } else {
    return JsxRuntime.jsx("span", {
      children: text
    });
  }
}

let make = MarqueeText;

export {
  make,
}
/* react Not a pure module */
