// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Ipod_moonbitJs from "../js/ipod_moonbit.js";

function defaultModelJsonRaw(prim) {
  return Ipod_moonbitJs.default_model_json();
}

function reduceModelRaw(prim0, prim1, prim2) {
  return Ipod_moonbitJs.reduce_model(prim0, prim1, prim2);
}

function authenticFinishesRaw(prim) {
  return Ipod_moonbitJs.get_authentic_finishes();
}

function deriveWheelRaw(prim) {
  return Ipod_moonbitJs.derive_wheel_json(prim);
}

function marqueeCycleMsRaw(prim0, prim1, prim2) {
  return Ipod_moonbitJs.marquee_cycle_ms(prim0, prim1, prim2);
}

function marqueeFrameRaw(prim0, prim1) {
  return Ipod_moonbitJs.marquee_frame(prim0, prim1);
}

function marqueeNeededRaw(prim0, prim1) {
  return Ipod_moonbitJs.marquee_needed(prim0, prim1);
}

function colorIsDarkRaw(prim) {
  return Ipod_moonbitJs.color_is_dark(prim);
}

function getStr(dict, key) {
  let match = dict[key];
  if (typeof match === "string") {
    return match;
  } else {
    return "";
  }
}

function getFloat(dict, key) {
  let match = dict[key];
  if (match !== undefined) {
    if (typeof match === "number") {
      return match;
    } else {
      return 0.0;
    }
  } else {
    return 0.0;
  }
}

function getInt(dict, key) {
  return getFloat(dict, key) | 0;
}

function getBool(dict, key) {
  let match = dict[key];
  return match === true;
}

function parseViewMode(s) {
  switch (s) {
    case "3d" :
      return "ThreeD";
    case "ascii" :
      return "Ascii";
    case "focus" :
      return "Focus";
    case "preview" :
      return "Preview";
    default:
      return "Flat";
  }
}

function parseHardwarePreset(s) {
  switch (s) {
    case "classic-2007" :
      return "Classic2007";
    case "classic-2008-black" :
      return "Classic2008Black";
    case "classic-2008-silver" :
      return "Classic2008Silver";
    case "classic-2009" :
      return "Classic2009";
    default:
      return "Classic2008";
  }
}

function parseInteractionModel(s) {
  switch (s) {
    case "ipod-os" :
      return "IpodOs";
    case "ipod-os-original" :
      return "IpodOsOriginal";
    default:
      return "Direct";
  }
}

function parseOsScreen(s) {
  if (s === "now-playing") {
    return "NowPlaying";
  } else {
    return "Menu";
  }
}

function parseSelectionKind(s) {
  if (s === "range") {
    return "Range";
  } else {
    return "Moment";
  }
}

function parseSongMetadata(d) {
  return {
    title: getStr(d, "title"),
    artist: getStr(d, "artist"),
    album: getStr(d, "album"),
    artwork: getStr(d, "artwork"),
    duration: getFloat(d, "duration"),
    currentTime: getFloat(d, "currentTime"),
    rating: getFloat(d, "rating") | 0,
    trackNumber: getFloat(d, "trackNumber") | 0,
    totalTracks: getFloat(d, "totalTracks") | 0
  };
}

function parsePresentation(d) {
  return {
    skinColor: getStr(d, "skinColor"),
    bgColor: getStr(d, "bgColor"),
    viewMode: parseViewMode(getStr(d, "viewMode")),
    hardwarePreset: parseHardwarePreset(getStr(d, "hardwarePreset"))
  };
}

function parseInteraction(d) {
  return {
    interactionModel: parseInteractionModel(getStr(d, "interactionModel")),
    osScreen: parseOsScreen(getStr(d, "osScreen")),
    menuIndex: getFloat(d, "menuIndex") | 0,
    osOriginalMenuSplit: getFloat(d, "osOriginalMenuSplit"),
    isNowPlayingEditable: getBool(d, "isNowPlayingEditable"),
    isPlaying: getBool(d, "isPlaying"),
    batteryLevel: getFloat(d, "batteryLevel")
  };
}

function parsePlayback(d) {
  return {
    currentTime: getFloat(d, "currentTime"),
    duration: getFloat(d, "duration"),
    selectionKind: parseSelectionKind(getStr(d, "selectionKind")),
    rangeStartTime: getFloat(d, "rangeStartTime"),
    rangeEndTime: getFloat(d, "rangeEndTime")
  };
}

function parseIpModel(_raw) {
  while (true) {
    let raw = _raw;
    let d = JSON.parse(raw);
    if (typeof d === "object" && d !== null && !Array.isArray(d)) {
      let match = d["metadata"];
      let tmp;
      tmp = match !== undefined ? (
          typeof match === "object" && match !== null && !Array.isArray(match) ? parseSongMetadata(match) : parseSongMetadata({})
        ) : parseSongMetadata({});
      let match$1 = d["presentation"];
      let tmp$1;
      tmp$1 = match$1 !== undefined ? (
          typeof match$1 === "object" && match$1 !== null && !Array.isArray(match$1) ? parsePresentation(match$1) : parsePresentation({})
        ) : parsePresentation({});
      let match$2 = d["interaction"];
      let tmp$2;
      tmp$2 = match$2 !== undefined ? (
          typeof match$2 === "object" && match$2 !== null && !Array.isArray(match$2) ? parseInteraction(match$2) : parseInteraction({})
        ) : parseInteraction({});
      let match$3 = d["playback"];
      let tmp$3;
      tmp$3 = match$3 !== undefined ? (
          typeof match$3 === "object" && match$3 !== null && !Array.isArray(match$3) ? parsePlayback(match$3) : parsePlayback({})
        ) : parsePlayback({});
      return {
        metadata: tmp,
        presentation: tmp$1,
        interaction: tmp$2,
        playback: tmp$3
      };
    }
    _raw = "{}";
    continue;
  };
}

function parseDispatchResult(raw) {
  let d = JSON.parse(raw);
  if (typeof d !== "object" || d === null || Array.isArray(d)) {
    return {
      model: parseIpModel("{}"),
      effects: []
    };
  }
  let match = d["model"];
  let tmp;
  tmp = typeof match === "object" && match !== null && !Array.isArray(match) ? parseIpModel(raw) : parseIpModel("{}");
  let match$1 = d["effects"];
  let tmp$1;
  tmp$1 = Array.isArray(match$1) ? Belt_Array.map(match$1, v => {
      if (typeof v === "string") {
        return v;
      } else {
        return "";
      }
    }) : Belt_Array.make(0, "");
  return {
    model: tmp,
    effects: tmp$1
  };
}

function parseFinishes(raw) {
  let arr = JSON.parse(raw);
  if (Array.isArray(arr)) {
    return Belt_Array.map(arr, v => {
      if (typeof v === "object" && v !== null && !Array.isArray(v)) {
        return {
          label: getStr(v, "label"),
          hex: getStr(v, "hex")
        };
      } else {
        return {
          label: "",
          hex: "#000000"
        };
      }
    });
  } else {
    return [];
  }
}

function parseWheelColors(raw) {
  let d = JSON.parse(raw);
  if (typeof d === "object" && d !== null && !Array.isArray(d)) {
    return {
      labelColor: getStr(d, "labelColor"),
      borderColor: getStr(d, "borderColor"),
      centerBorder: getStr(d, "centerBorder"),
      centerGradient: getStr(d, "centerGradient")
    };
  } else {
    return {
      labelColor: "#FFFFFF",
      borderColor: "#555555",
      centerBorder: "#444444",
      centerGradient: "#666666"
    };
  }
}

function eventToTagData(event) {
  if (typeof event !== "object") {
    switch (event) {
      case "ToggleOsNowPlayingEditable" :
        return [
          "TOGGLE_OS_NOW_PLAYING_EDITABLE",
          ""
        ];
      case "ToggleIsPlaying" :
        return [
          "TOGGLE_IS_PLAYING",
          ""
        ];
      case "ResetModel" :
        return [
          "RESET_MODEL",
          ""
        ];
      case "ApplySongSnapshot" :
        return [
          "APPLY_SONG_SNAPSHOT",
          "{}"
        ];
    }
  } else {
    switch (event.TAG) {
      case "UpdateTitle" :
        return [
          "UPDATE_TITLE",
          event._0
        ];
      case "UpdateArtist" :
        return [
          "UPDATE_ARTIST",
          event._0
        ];
      case "UpdateAlbum" :
        return [
          "UPDATE_ALBUM",
          event._0
        ];
      case "UpdateArtwork" :
        return [
          "UPDATE_ARTWORK",
          event._0
        ];
      case "UpdateDuration" :
        return [
          "UPDATE_DURATION",
          event._0.toString()
        ];
      case "UpdateCurrentTime" :
        return [
          "UPDATE_CURRENT_TIME",
          event._0.toString()
        ];
      case "UpdateRating" :
        return [
          "UPDATE_RATING",
          event._0.toString()
        ];
      case "UpdateTrackNumber" :
        return [
          "UPDATE_TRACK_NUMBER",
          event._0.toString()
        ];
      case "UpdateTotalTracks" :
        return [
          "UPDATE_TOTAL_TRACKS",
          event._0.toString()
        ];
      case "SetViewMode" :
        let tmp;
        switch (event._0) {
          case "Flat" :
            tmp = "flat";
            break;
          case "Focus" :
            tmp = "focus";
            break;
          case "Preview" :
            tmp = "preview";
            break;
          case "Ascii" :
            tmp = "ascii";
            break;
          case "ThreeD" :
            tmp = "3d";
            break;
        }
        return [
          "SET_VIEW_MODE",
          tmp
        ];
      case "SetSkinColor" :
        return [
          "SET_SKIN_COLOR",
          event._0
        ];
      case "SetBgColor" :
        return [
          "SET_BG_COLOR",
          event._0
        ];
      case "SetHardwarePreset" :
        let tmp$1;
        switch (event._0) {
          case "Classic2007" :
            tmp$1 = "classic-2007";
            break;
          case "Classic2008" :
            tmp$1 = "classic-2008";
            break;
          case "Classic2009" :
            tmp$1 = "classic-2009";
            break;
          case "Classic2008Black" :
            tmp$1 = "classic-2008-black";
            break;
          case "Classic2008Silver" :
            tmp$1 = "classic-2008-silver";
            break;
        }
        return [
          "SET_HARDWARE_PRESET",
          tmp$1
        ];
      case "SetInteractionModel" :
        let tmp$2;
        switch (event._0) {
          case "Direct" :
            tmp$2 = "direct";
            break;
          case "IpodOs" :
            tmp$2 = "ipod-os";
            break;
          case "IpodOsOriginal" :
            tmp$2 = "ipod-os-original";
            break;
        }
        return [
          "SET_INTERACTION_MODEL",
          tmp$2
        ];
      case "SetOsScreen" :
        let tmp$3;
        tmp$3 = event._0 === "Menu" ? "menu" : "now-playing";
        return [
          "SET_OS_SCREEN",
          tmp$3
        ];
      case "SetOsMenuIndex" :
        return [
          "SET_OS_MENU_INDEX",
          event._0.toString()
        ];
      case "CycleOsMenu" :
        return [
          "CYCLE_OS_MENU",
          event._0.toString()
        ];
      case "SetOsOriginalMenuSplit" :
        return [
          "SET_OS_ORIGINAL_MENU_SPLIT",
          event._0.toString()
        ];
      case "SetOsNowPlayingEditable" :
        return [
          "SET_OS_NOW_PLAYING_EDITABLE",
          event._0 ? "true" : "false"
        ];
      case "SetIsPlaying" :
        return [
          "SET_IS_PLAYING",
          event._0 ? "true" : "false"
        ];
      case "SetBatteryLevel" :
        return [
          "SET_BATTERY_LEVEL",
          event._0.toString()
        ];
      case "SetSelectionKind" :
        let tmp$4;
        tmp$4 = event._0 === "Moment" ? "moment" : "range";
        return [
          "SET_SELECTION_KIND",
          tmp$4
        ];
      case "SetRangeStartTime" :
        return [
          "SET_RANGE_START_TIME",
          event._0.toString()
        ];
      case "SetRangeEndTime" :
        return [
          "SET_RANGE_END_TIME",
          event._0.toString()
        ];
      case "RestoreModel" :
        return [
          "RESTORE_MODEL",
          ""
        ];
    }
  }
}

function serializeModel(model) {
  let meta = model.metadata;
  let pres = model.presentation;
  let inter = model.interaction;
  let pb = model.playback;
  let match = pres.viewMode;
  let viewModeStr;
  switch (match) {
    case "Flat" :
      viewModeStr = "flat";
      break;
    case "Focus" :
      viewModeStr = "focus";
      break;
    case "Preview" :
      viewModeStr = "preview";
      break;
    case "Ascii" :
      viewModeStr = "ascii";
      break;
    case "ThreeD" :
      viewModeStr = "3d";
      break;
  }
  let match$1 = pres.hardwarePreset;
  let presetStr;
  switch (match$1) {
    case "Classic2007" :
      presetStr = "classic-2007";
      break;
    case "Classic2008" :
      presetStr = "classic-2008";
      break;
    case "Classic2009" :
      presetStr = "classic-2009";
      break;
    case "Classic2008Black" :
      presetStr = "classic-2008-black";
      break;
    case "Classic2008Silver" :
      presetStr = "classic-2008-silver";
      break;
  }
  let match$2 = inter.interactionModel;
  let imStr;
  switch (match$2) {
    case "Direct" :
      imStr = "direct";
      break;
    case "IpodOs" :
      imStr = "ipod-os";
      break;
    case "IpodOsOriginal" :
      imStr = "ipod-os-original";
      break;
  }
  let match$3 = inter.osScreen;
  let osStr;
  osStr = match$3 === "Menu" ? "menu" : "now-playing";
  let match$4 = pb.selectionKind;
  let selStr;
  selStr = match$4 === "Moment" ? "moment" : "range";
  let metaObj = {};
  metaObj["title"] = meta.title;
  metaObj["artist"] = meta.artist;
  metaObj["album"] = meta.album;
  metaObj["artwork"] = meta.artwork;
  metaObj["duration"] = meta.duration;
  metaObj["currentTime"] = meta.currentTime;
  metaObj["rating"] = meta.rating;
  metaObj["trackNumber"] = meta.trackNumber;
  metaObj["totalTracks"] = meta.totalTracks;
  let presObj = {};
  presObj["skinColor"] = pres.skinColor;
  presObj["bgColor"] = pres.bgColor;
  presObj["viewMode"] = viewModeStr;
  presObj["hardwarePreset"] = presetStr;
  let interObj = {};
  interObj["interactionModel"] = imStr;
  interObj["osScreen"] = osStr;
  interObj["menuIndex"] = inter.menuIndex;
  interObj["osOriginalMenuSplit"] = inter.osOriginalMenuSplit;
  interObj["isNowPlayingEditable"] = inter.isNowPlayingEditable;
  interObj["isPlaying"] = inter.isPlaying;
  interObj["batteryLevel"] = inter.batteryLevel;
  let pbObj = {};
  pbObj["currentTime"] = pb.currentTime;
  pbObj["duration"] = pb.duration;
  pbObj["selectionKind"] = selStr;
  pbObj["rangeStartTime"] = pb.rangeStartTime;
  pbObj["rangeEndTime"] = pb.rangeEndTime;
  let root = {};
  root["metadata"] = metaObj;
  root["presentation"] = presObj;
  root["interaction"] = interObj;
  root["playback"] = pbObj;
  return JSON.stringify(root);
}

function defaultModel() {
  return parseIpModel(Ipod_moonbitJs.default_model_json());
}

function reduce(model, event) {
  let modelJson = serializeModel(model);
  let match = eventToTagData(event);
  return parseDispatchResult(Ipod_moonbitJs.reduce_model(modelJson, match[0], match[1]));
}

function authenticFinishes() {
  return parseFinishes(Ipod_moonbitJs.get_authentic_finishes());
}

function deriveWheelColors(caseHex) {
  return parseWheelColors(Ipod_moonbitJs.derive_wheel_json(caseHex));
}

let marqueeCycleMs = marqueeCycleMsRaw;

let marqueeFrame = marqueeFrameRaw;

let marqueeNeeded = marqueeNeededRaw;

let colorIsDark = colorIsDarkRaw;

export {
  defaultModelJsonRaw,
  reduceModelRaw,
  authenticFinishesRaw,
  deriveWheelRaw,
  marqueeCycleMsRaw,
  marqueeFrameRaw,
  marqueeNeededRaw,
  colorIsDarkRaw,
  getStr,
  getFloat,
  getInt,
  getBool,
  parseViewMode,
  parseHardwarePreset,
  parseInteractionModel,
  parseOsScreen,
  parseSelectionKind,
  parseSongMetadata,
  parsePresentation,
  parseInteraction,
  parsePlayback,
  parseIpModel,
  parseDispatchResult,
  parseFinishes,
  parseWheelColors,
  eventToTagData,
  serializeModel,
  defaultModel,
  reduce,
  authenticFinishes,
  deriveWheelColors,
  marqueeCycleMs,
  marqueeFrame,
  marqueeNeeded,
  colorIsDark,
}
/* ../js/ipod_moonbit.js Not a pure module */
