// Generated by ReScript, PLEASE EDIT WITH CARE


let getItem = (function(key) {
    try { return localStorage.getItem(key); } catch(e) { return undefined; }
  });

let setItem = (function(key, value) {
    try { localStorage.setItem(key, value); } catch(e) {}
  });

function loadModel() {
  getItem("v0-ipod-metadata");
  getItem("v0-ipod-ui-state");
}

function setMetadata(_meta) {
  
}

function setUiState(_pres, _inter) {
  
}

export {
  getItem,
  setItem,
  loadModel,
  setMetadata,
  setUiState,
}
/* No side effect */
